# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by default the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBankImport"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-24"
  enabled:
    manager: true
    database: true
    producer: true
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: "${itembank.group}"
    accessKey: "${IAT_AWS_ACCESS_KEY}"
    secretKey: "${IAT_AWS_ACCESS_SECRET}"
  events:
    exchange: "iat_item_event_exchange"
    queue: "iat_item_event_queue"
    eventKey: "iat.item.event.*"
    error-queue: "iat_item_event_queue.dlq"
    error-event-key: "error.iat.item.event.*"

logging:
  level:
    org:
      opentestsystem:
        ap:
          itemimport: "debug"
          common: "info"

item-import:
  systemUsername: "item-import@smarterbalanced.org"
  systemFullname: "Item Import"
  importEnabled: true
  deleteIfExists: true
  deleteSleepTimeout: 4
  localBaseDir: "${HOME}/ItemImportTemp"
  itemSourceDir: "${HOME}/ItemImportSource/prod/items"
  stimuliSourceDir: "${HOME}/ItemImportSource/prod/stimuli"
  wordlistSourceDir: "${HOME}/ItemImportSource/prod/wordlists"
  includeFile: "import-ids.txt"
  numberOfThreads: 4
  publishReportEnabled: true
  workflowMapping:
    "Operational": "Operational"
    "Ready For Field Test": "FieldTestReady"
    "Field Test Pool": "FieldTest"
    "Archetypes": "Archived"
    "Revise Review": ""
    "Data Review": "DataReview"
    "Locked Operational - NonSBAC": "Operational"
    "Locked Operational Pool": "Operational"
    "Released": "Released"
    "Released Status": "Released"
    "Rejected": "Rejected"
    "Rejected Status": "Rejected"
    "Not Submit Status": "Rejected"
    "Locked Operational - Non SBAC": ""
    "Locked Operational Pool: Post QC": ""
    "Field Test Pool: Post QC": "FieldTest"
    "Stimulus: Field Test Pool": "FieldTest"
    "Stimulus: Archetypes": "Archived"
    "Stimulus: Revise Review": ""
    "Stimulus: Locked Operational - NonSBAC": "Operational"
    "Stimulus: Locked Operational Pool": "Operational"
    "Stimulus: Released Status": "Released"
    "Stimulus: Locked Operational - Non SBAC": ""
    "Stimulus: Locked Operational Pool: Post QC": ""
    "Stimulus: Field Test Pool: Post QC": "FieldTest"
    "Stimulus: Locked Interim Pool: Post QC": ""
    "Lab/Trial Ready": "Released"
    "Lock": "Released"
    "Stimulus: Lab/Trial Ready": "Released"



---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

itembank:
  group: "iat-development"

---
spring:
  profiles: uat
  datasource:
    url: "jdbc:postgresql://imrt-db-uat-aurora.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

itembank:
  group: "iat-uat"